apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "new-namespace.fullname" . }}-limit-range
  namespace: {{ include "new-namespace.fullname" . }}
spec:
  limits:
    - type: Container
      {{- toYaml .Values.limits | nindent 6 }}
