apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "new-namespace.fullname" . }}-limit-range
  namespace: {{ include "new-namespace.fullname" . }}
spec:
  limits:
  - name: resource-limits
    limit:
      - type: Container
        {{- toYaml .Values.limits | nindent 8 }}
