apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "new-namespace.fullname" . }}-extend
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ include "new-namespace.fullname" . }}
  project: default
  source:
    path: {{ include "new-namespace.fullname" . }}
    repoURL: {{ .Values.mainRepo }}
    targetRevision: cluster-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
