apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "deploypackage.fullname" . }}-extras
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ include "deploypackage.fullname" . }}
  project: default
  source:
    path: {{ .Release.Namespace }}/{{ include "deploypackage.fullname" . }}
    repoURL: {{ include "deploypackage.mainRepo" . }}
    targetRevision: {{ include "deploypackage.mainRevision" . }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
