apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-{{ include "deploypackage.fullname" . }}-extras
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Release.Namespace }}
  project: default
  source:
    path: {{ .Release.Namespace }}/{{ include "deploypackage.fullname" . }}
    repoURL: {{ .Values.mainRepo }}
    targetRevision: {{ .Values.mainRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
